;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;
;;             POLYBAR - MINIMAL EDITION
;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

include-file = ~/.config/polybar/colors.ini
include-file = ~/.config/polybar/modules.ini

[bar/main]
width = 100%
height = 27
offset-x = 0
offset-y = 0
radius = 0
bottom = true
fixed-center = true
background = ${colors.background}
foreground = ${colors.foreground}
border-size = 0
line-size = 0
padding-left = 2
padding-right = 2
module-margin = 3
separator =
font-0 = Iosevka Term Light:size=10;2
wm-restack = i3
override-redirect = false
enable-ipc = true
cursor-click = pointer
cursor-scroll = ns-resize
modules-left = workspaces
modules-center = title
modules-right = date
